[general]
import = ["~/.config/alacritty/themes/themes/shkesh.toml"]

[window]
padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

[colors.primary]
background = '#0C0D11'

[font]
normal = {family = "Roboto Mono", style = "Medium" }
bold = { family = "Roboto Mono", style = "Bold" }
italic = { family = "Roboto Mono", style = "Medium" }
bold_italic = { family = "Roboto Mono", style = "Bold" }

size = 14.0
